import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Layout } from "antd";
import type { Metadata } from "next";
import { Inter, Oswald } from "next/font/google";
import "./globals.css";
const { Content } = Layout;

const inter = Inter({ subsets: ["latin"] });

const oswald = Oswald({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Slack web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={oswald.className}>
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
